lbfgs: fix check_work
I got this error, which doesn't make sense because 2 is <= 2:
```
Fatal error: exception Failure("Lbfgs.min: dim of work too small for problem size n = 2, valid n <= 2")
```

iwa is allocated as 3*n, and upstream L-BFGS-ocaml checks for 3*n too,
the check against 3*corrections seems to be a typo, looking at lbfgsb.f
says '3*nmax' and the code has `iwa.(2*n+1)` so clearly related to 'n'
and not 'corrections'.

Signed-off-by: Edwin Török <edwin@etorok.net>