OCaml 5.0 compatibility: copy_double -> caml_copy_double
'caml_copy_double' has been present since OCaml 3.08.
'copy_double' was a deprecated alias, which got dropped in OCaml 5.0.

Fixes the following runtime error from the linker:
```
undefined reference to `copy_double'
```

'dune runtest' passes on OCaml 5.0 now.

Signed-off-by: Edwin Török <edwin@etorok.net>
(cherry picked from commit cf042bc4e09bc9e39bd5df18df00649af3c356c5)